name: Run E2E Tests

on: [push]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run test:e2e
        env:
          API_PORT: "3000"
          EMAIL_PROVIDER_HOST: "smtp.gmail.com"
          EMAIL_PROVIDER_PORT: "465"
          EMAIL_PROVIDER_SSL: "true"
          EMAIL_PROVIDER_ADDRESS: "${{ secrets.EMAIL_PROVIDER_ADDRESS }}"
          EMAIL_PROVIDER_PASSWORD: "${{ secrets.EMAIL_PROVIDER_PASSWORD }}"
          MY_EMAIL_ADDRESS: "${{ secrets.MY_EMAIL_ADDRESS }}"
          NODE_ENV: "test"